boop.ui = boop.ui or {}
boop.config = boop.config or {}

boop.config.schema = boop.config.schema or {
  order = {
    "enabled",
    "targetingMode",
    "useQueueing",
    "prequeueEnabled",
    "attackLeadSeconds",
    "autoGrabGold",
    "goldPack",
    "whitelistPriorityOrder",
    "retargetOnPriority",
    "targetOrder",
    "attackMode",
    "pullRageReserve",
    "fleeEnabled",
    "fleeAt",
    "tempoRageWindowSeconds",
    "tempoSqueezeEtaSeconds",
    "focusVerb",
    "traceEnabled",
    "gagOwnAttacks",
    "gagOthersAttacks",
    "gagColorWho",
    "gagColorAbility",
    "gagColorTarget",
    "gagColorMeta",
    "gagColorSeparator",
    "gagColorBackground",
    "gagOtherColorWho",
    "gagOtherColorAbility",
    "gagOtherColorTarget",
    "gagOtherColorMeta",
    "gagOtherColorSeparator",
    "gagOtherColorBackground",
    "diagTimeoutSeconds",
    "partySize",
    "partyRoster",
    "targetCall",
    "autoTargetCall",
    "rageAffCalloutsEnabled",
    "assistEnabled",
    "assistLeader",
    "uiTheme",
    "gameSeparator",
  },
  aliases = {
    enabled = "enabled",
    targeting = "targetingMode",
    targetingmode = "targetingMode",
    usequeueing = "useQueueing",
    queueing = "useQueueing",
    prequeue = "prequeueEnabled",
    prequeueenabled = "prequeueEnabled",
    lead = "attackLeadSeconds",
    attacklead = "attackLeadSeconds",
    attackleadseconds = "attackLeadSeconds",
    autogold = "autoGrabGold",
    autograbgold = "autoGrabGold",
    pack = "goldPack",
    goldpack = "goldPack",
    whitelistpriorityorder = "whitelistPriorityOrder",
    retargetonpriority = "retargetOnPriority",
    retargetpriority = "retargetOnPriority",
    stickytarget = "retargetOnPriority",
    stickyoncurrent = "retargetOnPriority",
    targetorder = "targetOrder",
    ragemode = "attackMode",
    attackmode = "attackMode",
    trace = "traceEnabled",
    traceenabled = "traceEnabled",
    gag = "gagOwnAttacks",
    gagown = "gagOwnAttacks",
    gagownattacks = "gagOwnAttacks",
    gagothers = "gagOthersAttacks",
    gagothersattacks = "gagOthersAttacks",
    gagcolorwho = "gagColorWho",
    gagcolorability = "gagColorAbility",
    gagcolortarget = "gagColorTarget",
    gagcolormeta = "gagColorMeta",
    gagcolorseparator = "gagColorSeparator",
    gagcolorbg = "gagColorBackground",
    gagcolorbackground = "gagColorBackground",
    gagothercolorwho = "gagOtherColorWho",
    gagothercolorability = "gagOtherColorAbility",
    gagothercolortarget = "gagOtherColorTarget",
    gagothercolormeta = "gagOtherColorMeta",
    gagothercolorseparator = "gagOtherColorSeparator",
    gagothercolorbg = "gagOtherColorBackground",
    gagothercolorbackground = "gagOtherColorBackground",
    diagtimeout = "diagTimeoutSeconds",
    diagtimeoutseconds = "diagTimeoutSeconds",
    partysize = "partySize",
    partycount = "partySize",
    groupsize = "partySize",
    party = "partyRoster",
    partyroster = "partyRoster",
    assist = "assistEnabled",
    assistenabled = "assistEnabled",
    assistleader = "assistLeader",
    leader = "assistLeader",
    autotargetcall = "autoTargetCall",
    autocall = "autoTargetCall",
    leaderautocall = "autoTargetCall",
    leadermode = "autoTargetCall",
    leadtargets = "autoTargetCall",
    pullreserve = "pullRageReserve",
    pullragereserve = "pullRageReserve",
    flee = "fleeEnabled",
    fleeenabled = "fleeEnabled",
    fleeat = "fleeAt",
    theme = "uiTheme",
    uitheme = "uiTheme",
    targetcall = "targetCall",
    leadertargetcall = "targetCall",
    affcalls = "rageAffCalloutsEnabled",
    rageaffcalls = "rageAffCalloutsEnabled",
    rageaffcallouts = "rageAffCalloutsEnabled",
    partyaffcalls = "rageAffCalloutsEnabled",
    tempowindow = "tempoRageWindowSeconds",
    temporagewindow = "tempoRageWindowSeconds",
    temporagewindowseconds = "tempoRageWindowSeconds",
    tempoeta = "tempoSqueezeEtaSeconds",
    temposqueezeeta = "tempoSqueezeEtaSeconds",
    temposqueezeetaseconds = "tempoSqueezeEtaSeconds",
    gameseparator = "gameSeparator",
    focus = "focusVerb",
    focusverb = "focusVerb",
  },
}

boop.ui.modes = boop.ui.modes or {
  solo = {
    key = "solo",
    requiresLeader = false,
    summary = "Disable assist and leader target coordination.",
    values = {
      assistEnabled = false,
      autoTargetCall = false,
      targetCall = false,
    },
    clearTargetCall = true,
    message = function()
      return "mode: solo"
    end,
  },
  assist = {
    key = "assist",
    requiresLeader = true,
    summary = "Prefix attacks with assist and do not wait for leader target calls.",
    values = {
      assistEnabled = true,
      autoTargetCall = false,
      targetCall = false,
    },
    clearTargetCall = true,
    message = function(leader)
      return "mode: assist -> " .. tostring(leader)
    end,
  },
  leader = {
    key = "leader",
    aliases = { "leading" },
    requiresLeader = false,
    summary = "Automatically party-call each new target you engage.",
    values = {
      assistEnabled = false,
      autoTargetCall = true,
      targetCall = false,
    },
    clearTargetCall = true,
    message = function()
      return "mode: leader"
    end,
  },
  ["leader-call"] = {
    key = "leader-call",
    aliases = { "leadercall", "lead" },
    requiresLeader = true,
    summary = "Wait for a called target from your configured leader.",
    values = {
      assistEnabled = true,
      autoTargetCall = false,
      targetCall = true,
    },
    clearTargetCall = false,
    message = function(leader)
      return "mode: leader-call -> " .. tostring(leader)
    end,
  },
}

boop.ui.presets = boop.ui.presets or {
  solo = {
    label = "solo",
    summary = "Whitelist solo hunting with simple rage and no party gating.",
    values = {
      targetingMode = "whitelist",
      useQueueing = false,
      prequeueEnabled = true,
      attackLeadSeconds = 1,
      autoGrabGold = true,
      attackMode = "simple",
      partySize = 1,
      rageAffCalloutsEnabled = false,
      assistEnabled = false,
      autoTargetCall = false,
      targetCall = false,
    },
  },
  party = {
    label = "party",
    summary = "Party-friendly hunting without assist or leader target gating.",
    values = {
      targetingMode = "whitelist",
      useQueueing = false,
      prequeueEnabled = true,
      attackLeadSeconds = 1,
      autoGrabGold = true,
      attackMode = "simple",
      partySize = 2,
      rageAffCalloutsEnabled = false,
      assistEnabled = false,
      autoTargetCall = false,
      targetCall = false,
    },
  },
  leader = {
    label = "leader",
    summary = "Party hunting that automatically calls each new target you engage.",
    values = {
      targetingMode = "whitelist",
      useQueueing = false,
      prequeueEnabled = true,
      attackLeadSeconds = 1,
      autoGrabGold = true,
      attackMode = "simple",
      partySize = 2,
      rageAffCalloutsEnabled = false,
      assistEnabled = false,
      autoTargetCall = true,
      targetCall = false,
    },
  },
  ["leader-call"] = {
    label = "leader-call",
    summary = "Party hunting that waits for a called target from your configured leader.",
    values = {
      targetingMode = "whitelist",
      useQueueing = false,
      prequeueEnabled = true,
      attackLeadSeconds = 1,
      autoGrabGold = true,
      attackMode = "simple",
      partySize = 2,
      rageAffCalloutsEnabled = false,
      assistEnabled = true,
      autoTargetCall = false,
      targetCall = true,
    },
    requiresLeader = true,
  },
}

boop.ui.screens = boop.ui.screens or {
  configSections = {
    { id = 1, key = "combat", label = "Hunting", aliases = { "combat", "hunting", "queueing", "queue" } },
    { id = 2, key = "targeting", label = "Targeting", aliases = { "targeting", "targets" } },
    { id = 3, key = "loot", label = "Loot", aliases = { "loot", "gold", "import" } },
    { id = 4, key = "debug", label = "Diagnostics", aliases = { "debug", "diagnostics", "trace", "gag" } },
  },
  configHomeRoutes = {
    ["5"] = "party",
    party = "party",
    assist = "party",
    leader = "party",
    ["6"] = "roster",
    roster = "roster",
    ["7"] = "theme",
    theme = "theme",
    appearance = "theme",
    ["8"] = "control",
    control = "control",
    ["9"] = "stats",
    stats = "stats",
    mode = "mode",
  },
}
